repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        language_version: python3
        args: ["--profile", "black", "--line-length", "100"]

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3
        args: ["--line-length", "100"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.9
    hooks:
      - id: ruff

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint --rcfile .pylintrc src
        language: system
        types: [python]
        pass_filenames: false