repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        language_version: python3
        args: ["--profile", "black", "--line-length", "120"]

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3
        args: ["--line-length", "120"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.9
    hooks:
      - id: ruff
        args: ["--line-length=120"]

  - repo: local
    hooks:
      - id: test-coverage
        name: Test Coverage Check
        entry: bash -c "rm -f .coverage && coverage run -m pytest && coverage report --fail-under=90"
        language: system
        pass_filenames: false

  - repo: https://github.com/pylint-dev/pylint
    rev: v3.3.6
    hooks:
      - id: pylint
        name: Code Quality Check
        entry: pylint --rcfile .pylintrc --fail-under=10.0 src main.py
        exclude: '^tests/'
        language: system
